config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'items#index'
  resources :users, only:[:show, :edit]
  resources :items
  resources :categories, only:[:index, :show]
  resources :brands, only:[:index, :show]
  scope module: 'users' do
    resources :user_cards, only:[:edit, :update]
    resources :user_identifications, only:[:edit, :update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/user_cards_controller.rb
class Users::UserCardsController < ApplicationController
  def edit
  end

  def update
  end
end

app/controllers/users/user_identifications_controller.rb
class Users::UserIdentificationsController < ApplicationController
  def edit
  end

  def update
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.new
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/new.html.haml
.container
  = render "shared/second__header"
  .new-item__main
    .form
      .new-item__main__container
        .new-item__main__container__head
          %h2 商品の情報を入力
        .sell-form__image
          .sell-form__image__head
            %h3
              出品画像
            %span 必須
            %p 最大10枚までアップロードできます
          .sell-form__image__box
            -# = f.label :images do
            -#   = f.file_field :images, multiple: true
        .sell-form__content
          .sell-form__content__name
            %h5
              商品名
            %span 必須
          -# = f.text_field :name, class: "sell-form__content__name__wrap", placeholder: "商品名（必須 40文字まで)"
          .sell-form__content__description
            %h5
              商品の説明
            %span 必須
            -# = f.text_area :name, class: "sell-form__content__description__wrap", rows: "5", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"
        .sell-form__detail
          %h6 
            商品の詳細
          .sell-form__detail__form-box
            .sell-form__detail__form-box__category
              %h5
                カテゴリー
              %span 必須
            %select category
            .sell-form__detail__form-box__status
              %h5
                商品の状態
              %span 必須
            %select
        .sell-form__delivery
          %h3 
            配送について
            = link_to "?", "/", class: "question"
          .sell-form__delivery__form-box
            .sell-form__delivery__form-box__fee
              %h5
                配送料の負担
              %span 必須
            %select
            .sell-form__delivery__form-box__disrict
              %h5
                発送元の地域
              %span 必須
            %select
            .sell-form__delivery__form-box__date
              %h5
                発送までの日数
              %span 必須
            %select
        .sell-form__selling-price
          %h3
            販売価格(300〜9,999,999)
            = link_to "?", "/", class: "question"
          .sell-form__selling-price__box
            .sell-form__selling-price__input
              .sell-form__selling-price__input__left
                %h5
                  価格
                %span 必須
              .sell-form__selling-price__input__right
                %p 
                  ¥
                -# = f.text_field :name, class: "sell-form__selling-price__input__right__yen", placeholder: "例）300"
            .sell-form__selling-price__commission
              .sell-form__selling-price__commission__left
                %h6 販売手数料 (10%)
              .sell-form__selling-price__commission__right
                %h6 -
            .sell-form__selling-price__profit
              .sell-form__selling-price__profit__left
                %h6 販売利益
              .sell-form__selling-price__profit__right
                %h6 -
        .sell-form__submit
          = link_to "禁止されている商品", "https://www.mercari.com/jp/help_center/getting_started/prohibited_items/"
          、
          = link_to "行為", "https://www.mercari.com/jp/help_center/getting_started/prohibited_conduct/"
          を必ずご確認ください。
          %br 
            またブランド品でシリアルナンバー等がある場合はご記載ください。
            = link_to "偽ブランドの販売", "https://www.mercari.com/jp/help_center/getting_started/counterfeit_goods/"
            は犯罪であ
          り処罰される可能性があります。
          %br 
            また、出品を持ちまして
            = link_to "加盟店規約", "https://www.mercari.com/jp/seller_terms/"
            にも同意したことになります。
          .sell-form__submit__btn
            = link_to "出品する", "/", class: "sell-form__submit__red"
            = link_to "もどる", "/", class: "sell-form__submit__gray"
  = render "shared/second__footer"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FreemarketSmple52d
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/shared/_mypage_contents.html.haml
.contents
  %section.mypage-user-icon
    = link_to root_path, class:"mypage-user-icon__link" do
      %figure.mypage-user-icon__link__image
        = image_tag "", size: "60x60", alt: "figure", class: 'mypage-user-icon__image__figure'
      %h2.mypage-user-icon__link__user-name
        ユーザー名
      .mypage-user-icon__link__mypage-number
        .mypage-user-icon__link__mypage-number__rate
          評価
          %span.mypage-user-icon__link__mypage-number__rate__number
            108
        .mypage-user-icon__link__mypage-number__items
          出品数
          %span.mypage-user-icon__link__mypage-number__items__number
            108

  %section.mypage-tab
    %ul.mypage-tab__tabs
      %li.mypage-tab__tabs__left
        %h3.active-tab
          = link_to root_path, class:"mypage-tab__tabs__left__link" do
            お知らせ
      %li.mypage-tab__tabs__right
        %h3.none-active-tab
          = link_to root_path, class:"mypage-tab__tabs__right__link" do
            やることリスト
    .mypage-tab__contents
      %ul.mypage-tab__contents__notice-list.display-true
        %li.mypage-tab__contents__notice-list__item.display-true
          = link_to root_path, class:"mypage-tab__contents__notice-list__item__link" do
            %figure.mypage-tab__contents__notice-list__item__link__figure
              = image_tag "", size: "48x48", alt: "icon"
            .mypage-tab__contents__notice-list__item__link__body
              .mypage-tab__contents__notice-list__item__link__body__text
                《ご登録記念》¥1,000の商品を「実質１円」でご購入いただけます！
              %time.mypage-tab__contents__notice-list__item__link__body__time
                = fa_icon 'history'
                %span １日前
            %i.mypage-tab__contents__notice-list__item__link__icon-arrow-right
              = fa_icon 'chevron-right'
        %li.mypage-tab__contents__notice-list__go-to-index
          = link_to "一覧を見る", root_path, class:"mypage-tab__contents__notice-list__go-to-index__link"
        .mypage-tab__contents__none.display-true
          %li.mypage-tab__contents__none__text
            お知らせがありません
  %section.mypage-tab-deal
    %h2.mypage-tab-deal__title
      購入した商品
    %ul.mypage-tab__tabs
      %li.mypage-tab__tabs__left
        %h3.active-tab
          = link_to root_path, class:"mypage-tab__tabs__left__link" do
            取引中
      %li.mypage-tab__tabs__right
        %h3.none-active-tab
          = link_to root_path, class:"mypage-tab__tabs__right__link" do
            過去の取引

  %h2.set-profile-header
    プロフィール
  = form_for user_path do |f|
    .set-profile-upper
      %figure.set-profile-upper__avator
        = image_tag "", size: "60x60", alt: "figure"
      = f.text_field :name, placeholder: "例）AYA☆セール中", class: "set-profile-upper__form"
    .set-profile-lower
      = f.text_area :name, placeholder: "例）こんにちは☆ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪", class: "set-profile-lower__form"
      = f.submit class:"set-profile-lower__submit-button"

app/views/shared/_register-user.html.haml
%section.single-contents
  %h2.single-contents__header
    会員情報入力
  = form_for(resource, as: resource_name, url: registration_path(resource_name), :html=>{class: "single-contents__form", method: :put}) do |f|
    .single-contents__form__content
      .single-contents__form__content__upper
        = f.label :email, "ニックネーム", class: "single-contents__form__content__upper__label"
        .single-contents__form__content__upper__require-icon
          必須
      .single-contents__form__content__lower
        = f.text_field :email, class: "single-contents__form__content__lower__field", placeholder: "例）メルカリ太郎"
    .single-contents__form__content
      .single-contents__form__content__upper
        = f.label :email, "メールアドレス", class: "single-contents__form__content__upper__label"
        .single-contents__form__content__upper__require-icon
          必須
      .single-contents__form__content__lower
        = f.text_field :email, class: "single-contents__form__content__lower__field", placeholder: "PC・携帯どちらでも可"
    .single-contents__form__content
      .single-contents__form__content__upper
        = f.label :email, "パスワード", class: "single-contents__form__content__upper__label"
        .single-contents__form__content__upper__require-icon
          必須
      .single-contents__form__content__lower
        = f.text_field :email, class: "single-contents__form__content__lower__field", placeholder: "6文字以上"
    .single-contents__form__content
      .single-contents__form__content__upper
        = f.label :email, "パスワード(確認)", class: "single-contents__form__content__upper__label"
        .single-contents__form__content__upper__require-icon
          必須
      .single-contents__form__content__lower
        = f.text_field :email, class: "single-contents__form__content__lower__field", placeholder: "6文字以上"
    .single-contents__form__attend
      %h3.single-contents__form__attend__title
        本人確認
      %p.single-contents__form__attend__text
        安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
    .single-contents__form__content
      .single-contents__form__content__upper
        = f.label :email, "姓(全角)", class: "single-contents__form__content__upper__label"
        .single-contents__form__content__upper__require-icon
          必須
      .single-contents__form__content__lower
        = f.text_field :email, class: "single-contents__form__content__lower__field", placeholder: "例)山田"
    .single-contents__form__content
      .single-contents__form__content__upper
        = f.label :email, "名(全角)", class: "single-contents__form__content__upper__label"
        .single-contents__form__content__upper__require-icon
          必須
      .single-contents__form__content__lower
        = f.text_field :email, class: "single-contents__form__content__lower__field", placeholder: "例)彩"
    .single-contents__form__content
      .single-contents__form__content__upper
        = f.label :email, "姓カナ(全角)", class: "single-contents__form__content__upper__label"
        .single-contents__form__content__upper__require-icon
          必須
      .single-contents__form__content__lower
        = f.text_field :email, class: "single-contents__form__content__lower__field", placeholder: "例)ヤマダ"
    .single-contents__form__content
      .single-contents__form__content__upper
        = f.label :email, "名カナ(全角)", class: "single-contents__form__content__upper__label"
        .single-contents__form__content__upper__require-icon
          必須
      .single-contents__form__content__lower
        = f.text_field :email, class: "single-contents__form__content__lower__field", placeholder: "例)アヤ"
    .single-contents__form__content
      .single-contents__form__content__upper
        = f.label :email, "生年月日", class: "single-contents__form__content__upper__label"
        .single-contents__form__content__upper__require-icon
          必須
      .single-contents__form__content__lower-date
        = f.text_field :email, class: "single-contents__form__content__lower-date__field"
        %span.single-contents__form__content__lower-date__arrow-year
          = fa_icon 'chevron-down'
        %span.single-contents__form__content__lower-date__unit
          年
        = f.text_field :email, class: "single-contents__form__content__lower-date__field"
        %span.single-contents__form__content__lower-date__arrow-month
          = fa_icon 'chevron-down'
        %span.single-contents__form__content__lower-date__unit
          月
        = f.text_field :email, class: "single-contents__form__content__lower-date__field"
        %span.single-contents__form__content__lower-date__arrow-day
          = fa_icon 'chevron-down'
        %span.single-contents__form__content__lower-date__unit
          日
    .single-contents__form__attend
      %p.single-contents__form__attend__info-text
        ※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。
    .single-contents__form__recaptcha
    .single-contents__form__attend
      %p.single-contents__form__attend__next-text
        「次へ進む」のボタンを押すことにより、<a href="" class="single-contents__form__attend__next-text__link">利用規約</a>に同意したものとみなします
    = f.submit "次へ進む", class: "single-contents__form__submit"
    .single-contents__form__guid
      = link_to root_path, class: "single-contents__form__guid__link" do
        本人情報の登録について
        %i
          = fa_icon 'chevron-right'

app/views/shared/_register_address.html.haml
%section.single-contents
  %h2.single-contents__header
    住所入力
  = form_for(resource, as: resource_name, url: registration_path(resource_name), :html=>{class: "single-contents__form"}) do |f|
    .single-contents__form__content
      .single-contents__form__content__upper
        = f.label :email, "お名前", class: "single-contents__form__content__upper__label"
        .single-contents__form__content__upper__require-icon
          必須
      .single-contents__form__content__lower
        = f.text_field :email, class: "single-contents__form__content__lower__field", placeholder: "例）山田"
      .single-contents__form__content__lower
        = f.text_field :email, class: "single-contents__form__content__lower__field", placeholder: "例）彩"
    .single-contents__form__content
      .single-contents__form__content__upper
        = f.label :email, "お名前カナ", class: "single-contents__form__content__upper__label"
        .single-contents__form__content__upper__require-icon
          必須
      .single-contents__form__content__lower
        = f.text_field :email, class: "single-contents__form__content__lower__field", placeholder: "例）ヤマダ"
      .single-contents__form__content__lower
        = f.text_field :email, class: "single-contents__form__content__lower__field", placeholder: "例）アヤ"
    .single-contents__form__content
      .single-contents__form__content__upper
        = f.label :email, "郵便番号", class: "single-contents__form__content__upper__label"
        .single-contents__form__content__upper__require-icon
          必須
      .single-contents__form__content__lower
        = f.text_field :email, class: "single-contents__form__content__lower__field", placeholder: "例）123-4567"
    .single-contents__form__content
      .single-contents__form__content__upper
        = f.label :email, "都道府県", class: "single-contents__form__content__upper__label"
        .single-contents__form__content__upper__require-icon
          必須
      .single-contents__form__content__lower
        = f.text_field :email, class: "single-contents__form__content__lower__field", placeholder: "北海道"
      .single-contents__form__content__upper
        = f.label :email, "市区町村", class: "single-contents__form__content__upper__label"
        .single-contents__form__content__upper__require-icon
          必須
      .single-contents__form__content__lower
        = f.text_field :email, class: "single-contents__form__content__lower__field", placeholder: "例）横浜市緑区"
    .single-contents__form__content
      .single-contents__form__content__upper
        = f.label :email, "番地", class: "single-contents__form__content__upper__label"
        .single-contents__form__content__upper__require-icon
          必須
      .single-contents__form__content__lower
        = f.text_field :email, class: "single-contents__form__content__lower__field", placeholder: "例）青山1-1-1"
    .single-contents__form__content
      .single-contents__form__content__upper
        = f.label :email, "建物名", class: "single-contents__form__content__upper__label"
        .single-contents__form__content__upper__require-icon
          必須
      .single-contents__form__content__lower
        = f.text_field :email, class: "single-contents__form__content__lower__field", placeholder: "例）柳ビル103"
    .single-contents__form__content
      .single-contents__form__content__upper
        = f.label :email, "電話", class: "single-contents__form__content__upper__label"
        .single-contents__form__content__upper__require-icon
          必須
      .single-contents__form__content__lower
        = f.text_field :email, class: "single-contents__form__content__lower__field", placeholder: "例）09012345678"
    = f.submit "次へ進む", class: "single-contents__form__submit"

app/views/shared/_register_complete.html.haml
%section.single-contents
  %h2.single-contents__header
    会員登録完了
  .single-contents__form
    .single-contents__form__content
      %p.single-contents__form__content__text
        ありがとうございます。<br/>会員登録が完了しました。
    .single-contents__form__submit
      メルカリを始める
  .single-contents__advertisement

app/views/shared/_register_payment.html.haml
%section.single-contents
  %h2.single-contents__header
    支払い方法
  = form_for(resource, as: resource_name, url: registration_path(resource_name), :html=>{class: "single-contents__form"}) do |f|
    .single-contents__form__content
      .single-contents__form__content__upper
        = f.label :email, "カード番号", class: "single-contents__form__content__upper__label"
        .single-contents__form__content__upper__require-icon
          必須
      .single-contents__form__content__lower
        = f.text_field :email, class: "single-contents__form__content__lower__field", placeholder: "半角数字のみ"
    .single-contents__form__content
      .single-contents__form__content__upper
        = f.label :email, "有効期限", class: "single-contents__form__content__upper__label"
        .single-contents__form__content__upper__require-icon
          必須
      .single-contents__form__content__lower-effect
        = f.text_field :email, class: "single-contents__form__content__lower-effect__field", placeholder: "01"
        %span.single-contents__form__content__lower-effect__arrow
          = fa_icon 'chevron-down'
        %span.single-contents__form__content__lower-effect__unit
          月
      .single-contents__form__content__lower-effect
        = f.text_field :email, class: "single-contents__form__content__lower-effect__field", placeholder: "19"
        %span.single-contents__form__content__lower-effect__arrow
          = fa_icon 'chevron-down'
        %span.single-contents__form__content__lower-effect__unit
          年
    .single-contents__form__content
      .single-contents__form__content__upper
        = f.label :email, "セキュリティコード", class: "single-contents__form__content__upper__label"
        .single-contents__form__content__upper__require-icon
          必須
      .single-contents__form__content__lower
        = f.text_field :email, class: "single-contents__form__content__lower__field", placeholder: "カード背面4桁もしくは3桁の番号"
    .single-contents__form__guid
      = link_to root_path, class: "single-contents__form__guid__link" do
        %i
          = fa_icon 'question-circle'
        カード裏面の番号とは？
    = f.submit "次へ進む", class: "single-contents__form__submit"

app/views/shared/_register_phone_number.html.haml
%section.single-contents
  %h2.single-contents__header
    電話番号の確認
  = form_for(resource, as: resource_name, url: registration_path(resource_name), :html=>{class: "single-contents__form"}) do |f|
    .single-contents__form__content
      .single-contents__form__content__upper
        = f.label :email, "携帯電話の番号", class: "single-contents__form__content__upper__label"
      .single-contents__form__content__lower
        = f.text_field :email, class: "single-contents__form__content__lower__field", placeholder: "携帯電話の番号を入力"
    .single-contents__form__attend
      %p.single-contents__form__attend__info-text
        本人確認のため、携帯電話のSMS(ショートメッセージサービス)を利用して認証を行います。
    = f.submit "SMSを送信する", class: "single-contents__form__submit"
    .single-contents__form__attend
      %p.single-contents__form__attend__info-text
        ※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。
    .single-contents__form__guid
      = link_to root_path, class: "single-contents__form__guid__link" do
        電話番号の確認が必要な理由
        %i
          = fa_icon 'chevron-right'

app/views/shared/_second__footer.html.haml
.second__footer
  %nav
    %ul
      %li
        = link_to "プライバシーポリシー", "https://www.mercari.com/jp/privacy/"
      %li
        = link_to "メルカリ利用規約", "https://www.mercari.com/jp/tos/" 
      %li
        = link_to "特定商取引に関する表記", "https://www.mercari.com/jp/tokutei/"
  .second__footer__logo
    = link_to root_path do
      = image_tag('http://drive.google.com/uc?export=view&id=1B_AqSG4H4usXdquB0FBAsyaMzURKsJOE', alt: "mercari")
    %p
      %small ©︎2019 Mercari

app/views/shared/_second__header.html.haml
.second__header
  %h1
    %img(src="http://drive.google.com/uc?export=view&id=1U7dSgbjA26YwXkHqxRIVugpMN4BdERgY")

app/views/shared/_signup_header.html.haml
.signup
  .signup__header
    .signup__header__logo
      = link_to '#', class: "signup__header__logo__link" do
        = image_tag 'mercari_logo.svg'
    .signup__header__nav
      %ul.signup__header__nav__box
        %li.signup__header__nav__box__li
          会員情報
          .signup__header__nav__box__li__bottom.signup__header__nav__box__li__bottom__start
          .signup__header__nav__box__li__box
            .signup__header__nav__box__li__box__radius.signup__radius1.signup__header__nav__box__li__box__radius-red
        %li.signup__header__nav__box__li
          電話番号認証
          .signup__header__nav__box__li__bottom
          .signup__header__nav__box__li__box
            .signup__header__nav__box__li__box__radius.signup__radius2
        %li.signup__header__nav__box__li
          お届け先住所入力
          .signup__header__nav__box__li__bottom
          .signup__header__nav__box__li__box
            .signup__header__nav__box__li__box__radius.signup__radius3
        %li.signup__header__nav__box__li
          支払い方法
          .signup__header__nav__box__li__bottom
          .signup__header__nav__box__li__box
            .signup__header__nav__box__li__box__radius.signup__radius4
        %li.signup__header__nav__box__li
          完了
          .signup__header__nav__box__li__bottom.signup__header__nav__box__li__bottom__end
          .signup__header__nav__box__li__box
            .signup__header__nav__box__li__box__radius.signup__radius5

app/views/users/show.html.haml
.container
  = render "shared/mypage_side_bar"
  = render "shared/mypage_contents"
  = link_to root_path, class: "display-icon" do
    .display-icon__text
      ="出品"
    .display-icon__icon
      = fa_icon 'camera'

app/views/users/user_cards/index.html.haml
.card
  .card__top
    .card__top__title 支払い方法
  .card__main
    .card__main__box
      .card__main__box__left
        .card__main__box__left__title クレジットカード一覧
        .card__main__box__left__image
          = image_tag 'visa.svg', class: "card__main__box__left__image__box"
        .card__main__box__left__number **************7321
        .card__main__box__left__day 02/42
      .card__main__box__right
        .card__main__box__right__delete
          = link_to "削除する",'#', class: "card__main__box__right__delete__link"
  .card__bottom
    = link_to "支払い方法について", '#', class: "card__bottom__link"